[package]
name = "wordle-entropy-bin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wordle-entropy-core = { path = "../core", features = ["terminal"] }
plotters = "0.3.6"
varpro = "0.3.0"
nalgebra = "0.29"
num-traits = "0.2.14"
num = "0.4.0"
